// This file is autogenerated. Changes will be overwritten.
#include "IFAU5VTW44/moc_weight_panel_click.cpp"
#include "IFAU5VTW44/moc_weight_panel_manual.cpp"
#include "IFAU5VTW44/moc_wgt_render.cpp"
#include "EWIEGA46WW/moc_main_window.cpp"
#include "EWIEGA46WW/moc_paint_canvas.cpp"
